version: '3.8'
services:
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:server@db:5432/PostgreSQL
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=profile-photos
      - SECRET_KEY=your-secret-key
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend

  post_service:
    build: ./post_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:server@db:5432/PostgreSQL
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=post-photos
      - SECRET_KEY=your-secret-key
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend

  feed_service:
    build: ./feed_service
    ports:
      - "5003:5003"
    environment:
      - SECRET_KEY=your-secret-key
    depends_on:
      - post_service
      - friend_service
    networks:
      - backend

  friend_service:
    build: ./friend_service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgresql://postgres:server@db:5432/PostgreSQL
      - USER_SERVICE_URL=http://user_service:5001
      - SECRET_KEY=your-secret-key
    depends_on:
      db:
        condition: service_healthy
      user_service:
        condition: service_started
    networks:
      - backend

  sets_service:
    build: ./sets_service
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=postgresql://postgres:server@db:5432/PostgreSQL
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=set-photos
      - SECRET_KEY=your-secret-key
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=PostgreSQL
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - user_service
      - post_service
      - feed_service
      - friend_service
    networks:
      - backend

volumes:
  postgres_data:
  minio_data:

networks:
  backend:
    name: server_backend
    driver: bridge