global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:5001']

  - job_name: 'post_service'
    static_configs:
      - targets: ['post_service:5002']

  - job_name: 'feed_service'
    static_configs:
      - targets: ['feed_service:5003']

  - job_name: 'friend_service'
    static_configs:
      - targets: ['friend_service:5004']

  - job_name: 'sets_service'
    static_configs:
      - targets: ['sets_service:5005']


